#perbarisan
print('namaku Sholehan \naku seorang guru \naku mengajar matematika')
print('\n')
print('ini ganti baris ganda')
print ('\n')
#pewarnaan dengan kode \033[...;...;...m
print('\033[1mTulisan ini tebal')
print('\033[2mTulisan ini seharusnya bergaris bawah')
print('\033[3mTulisan ini miring')
print('\033[5mTulisan ini miring')
print ('\n')
print('\033[1;30mTulisan ini tebal miring warna hitam')
print('\033[1;31mTulisan ini tebal miring warna merah')
print('\033[1;32mTulisan ini tebal miring warna hijau')
print('\033[1;33mTulisan ini tebal miring warna kuning')
print('\033[1;34mTulisan ini tebal miring warna biru')
print('\033[1;35mTulisan ini tebal miring warna ungu')
print('\033[1;36mTulisan ini tebal miring warna ungu muda')
print ('\n')
print('\033[1;36;40mTulisan tebal miring warna putih belakang hitam')
print('\033[1;36;41mTulisan tebal miring warna putih belakang merah')
print('\033[1;36;42mTulisan tebal miring warna putih belakang hijau')
print('\033[1;36;43mTulisan tebal miring warna putih belakang kuning')
print('\033[1;36;44mTulisan tebal miring warna putih belakang biru')
print('\033[1;36;45mTulisan tebal miring warna putih belakang ungu')
print('\033[1;36;46mTulisan tebal miring warna putih belakang ungu muda')
print('\033[1;30;47mTulisan tebal miring warna hitam belakang putih')